import type { Metadata } from "next";
import { Gabarito, Lexend } from "next/font/google";
import "./globals.css";
import HomeNav from "@/components/layout/home-nav";

const gabarito = Gabarito({
  subsets: ["latin"],
});

const lexend = Lexend({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Life Levels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} ${lexend.className} antialiased bg-stone-50`}
      >
        <HomeNav />
        {children}
      </body>
    </html>
  );
}
